version: 2.1

orbs:
  android: circleci/android@2.0.3

parameters:
  run-Sem04-AND1-eRoto-job:
    type: boolean
    default: false

jobs:
  build-and-test-Sem4-AND1-eRoto:
    executor:
      name: android/android-machine
      tag: 2022.04.1

    working_directory: ~/repo/Sem04/AND1/eRoto

    steps:
      - checkout:
          path: ~/repo/

      - run:
          name: chmod permissions
          command: chmod +x ./gradlew

      - android/run-tests:
          test-command: ./gradlew test

      - android/start-emulator-and-run-tests:

          test-command: ./gradlew connectedAndroidTest
          system-image: system-images;android-32;google_apis;x86

workflows:
  rSem04-AND1-eRoto-wf:
    when: << pipeline.parameters.run-Sem04-AND1-eRoto-job >>
    jobs:
      - build-and-test-Sem4-AND1-eRoto
